// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package db

import (
	"context"
	"time"
)

const adminCountArticles = `-- name: AdminCountArticles :one
SELECT count(*) FROM articles
WHERE ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) AdminCountArticles(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountArticles, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountArticlesByStatus = `-- name: AdminCountArticlesByStatus :one
SELECT count(*) FROM articles WHERE status = $1
`

func (q *Queries) AdminCountArticlesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountArticlesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListArticles = `-- name: AdminListArticles :many

SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE ($3::text IS NULL OR a.status = $3::text)
ORDER BY a.created_at DESC, a.id
LIMIT $1 OFFSET $2
`

type AdminListArticlesParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

type AdminListArticlesRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

// Admin queries
func (q *Queries) AdminListArticles(ctx context.Context, arg AdminListArticlesParams) ([]AdminListArticlesRow, error) {
	rows, err := q.db.Query(ctx, adminListArticles, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListArticlesRow{}
	for rows.Next() {
		var i AdminListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminTotalViews = `-- name: AdminTotalViews :one
SELECT COALESCE(sum(view_count), 0)::bigint FROM articles
`

func (q *Queries) AdminTotalViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminTotalViews)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const archiveArticle = `-- name: ArchiveArticle :execrows
UPDATE articles SET status = 'ARCHIVED' WHERE id = $1
`

func (q *Queries) ArchiveArticle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, archiveArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT count(*) FROM articles WHERE status = 'PUBLISHED'
`

func (q *Queries) CountPublishedArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedArticlesByCategory = `-- name: CountPublishedArticlesByCategory :one
SELECT count(*) FROM articles WHERE status = 'PUBLISHED' AND category_id = $1
`

func (q *Queries) CountPublishedArticlesByCategory(ctx context.Context, categoryID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticlesByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedArticlesByProvince = `-- name: CountPublishedArticlesByProvince :one
SELECT count(*) FROM articles WHERE status = 'PUBLISHED' AND province = $1
`

func (q *Queries) CountPublishedArticlesByProvince(ctx context.Context, province *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticlesByProvince, province)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedArticlesByTag = `-- name: CountPublishedArticlesByTag :one
SELECT count(*) FROM articles a
JOIN article_tags at ON a.id = at.article_id
WHERE a.status = 'PUBLISHED' AND at.tag_id = $1
`

func (q *Queries) CountPublishedArticlesByTag(ctx context.Context, tagID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticlesByTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchArticles = `-- name: CountSearchArticles :one
SELECT count(*) FROM articles
WHERE status = 'PUBLISHED'
  AND search_vector @@ plainto_tsquery('vi', $1)
`

func (q *Queries) CountSearchArticles(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchArticles, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    id, title, slug, description, author_name,
    content_html, content_plain, status,
    province, district, ward, asset_type, plot_count, total_area,
    thumbnail_key, original_file_key, original_file_name, original_file_mime,
    legacy_id, legacy_file_key, category_id, published_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22
)
RETURNING id, title, slug, description, author_name, content_html, content_plain,
          status, published_at, province, district, ward, asset_type, plot_count,
          total_area, thumbnail_key, original_file_key, original_file_name, original_file_mime,
          legacy_id, legacy_file_key, view_count, category_id, created_at, updated_at,
          meta_description, auction_start, auction_end, venue_name, venue_address,
          starting_price, deposit_amount
`

type CreateArticleParams struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Description      string     `json:"description"`
	AuthorName       string     `json:"author_name"`
	ContentHtml      string     `json:"content_html"`
	ContentPlain     string     `json:"content_plain"`
	Status           string     `json:"status"`
	Province         *string    `json:"province"`
	District         *string    `json:"district"`
	Ward             *string    `json:"ward"`
	AssetType        *string    `json:"asset_type"`
	PlotCount        *int32     `json:"plot_count"`
	TotalArea        *string    `json:"total_area"`
	ThumbnailKey     *string    `json:"thumbnail_key"`
	OriginalFileKey  *string    `json:"original_file_key"`
	OriginalFileName *string    `json:"original_file_name"`
	OriginalFileMime *string    `json:"original_file_mime"`
	LegacyID         *int32     `json:"legacy_id"`
	LegacyFileKey    *string    `json:"legacy_file_key"`
	CategoryID       *string    `json:"category_id"`
	PublishedAt      *time.Time `json:"published_at"`
}

type CreateArticleRow struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Description      string     `json:"description"`
	AuthorName       string     `json:"author_name"`
	ContentHtml      string     `json:"content_html"`
	ContentPlain     string     `json:"content_plain"`
	Status           string     `json:"status"`
	PublishedAt      *time.Time `json:"published_at"`
	Province         *string    `json:"province"`
	District         *string    `json:"district"`
	Ward             *string    `json:"ward"`
	AssetType        *string    `json:"asset_type"`
	PlotCount        *int32     `json:"plot_count"`
	TotalArea        *string    `json:"total_area"`
	ThumbnailKey     *string    `json:"thumbnail_key"`
	OriginalFileKey  *string    `json:"original_file_key"`
	OriginalFileName *string    `json:"original_file_name"`
	OriginalFileMime *string    `json:"original_file_mime"`
	LegacyID         *int32     `json:"legacy_id"`
	LegacyFileKey    *string    `json:"legacy_file_key"`
	ViewCount        int32      `json:"view_count"`
	CategoryID       *string    `json:"category_id"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	MetaDescription  *string    `json:"meta_description"`
	AuctionStart     *time.Time `json:"auction_start"`
	AuctionEnd       *time.Time `json:"auction_end"`
	VenueName        *string    `json:"venue_name"`
	VenueAddress     *string    `json:"venue_address"`
	StartingPrice    *int64     `json:"starting_price"`
	DepositAmount    *int64     `json:"deposit_amount"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.AuthorName,
		arg.ContentHtml,
		arg.ContentPlain,
		arg.Status,
		arg.Province,
		arg.District,
		arg.Ward,
		arg.AssetType,
		arg.PlotCount,
		arg.TotalArea,
		arg.ThumbnailKey,
		arg.OriginalFileKey,
		arg.OriginalFileName,
		arg.OriginalFileMime,
		arg.LegacyID,
		arg.LegacyFileKey,
		arg.CategoryID,
		arg.PublishedAt,
	)
	var i CreateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AuthorName,
		&i.ContentHtml,
		&i.ContentPlain,
		&i.Status,
		&i.PublishedAt,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.AssetType,
		&i.PlotCount,
		&i.TotalArea,
		&i.ThumbnailKey,
		&i.OriginalFileKey,
		&i.OriginalFileName,
		&i.OriginalFileMime,
		&i.LegacyID,
		&i.LegacyFileKey,
		&i.ViewCount,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaDescription,
		&i.AuctionStart,
		&i.AuctionEnd,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartingPrice,
		&i.DepositAmount,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :execrows
DELETE FROM articles WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const featuredArticles = `-- name: FeaturedArticles :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.status = 'PUBLISHED' AND a.thumbnail_key IS NOT NULL
ORDER BY a.published_at DESC, a.id
LIMIT $1
`

type FeaturedArticlesRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

func (q *Queries) FeaturedArticles(ctx context.Context, limit int32) ([]FeaturedArticlesRow, error) {
	rows, err := q.db.Query(ctx, featuredArticles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeaturedArticlesRow{}
	for rows.Next() {
		var i FeaturedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT a.id, a.title, a.slug, a.description, a.author_name, a.content_html, a.content_plain,
       a.status, a.published_at, a.province, a.district, a.ward, a.asset_type, a.plot_count,
       a.total_area, a.thumbnail_key, a.original_file_key, a.original_file_name, a.original_file_mime,
       a.legacy_id, a.legacy_file_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.meta_description, a.auction_start, a.auction_end, a.venue_name, a.venue_address,
       a.starting_price, a.deposit_amount,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.id = $1
`

type GetArticleByIDRow struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Description      string     `json:"description"`
	AuthorName       string     `json:"author_name"`
	ContentHtml      string     `json:"content_html"`
	ContentPlain     string     `json:"content_plain"`
	Status           string     `json:"status"`
	PublishedAt      *time.Time `json:"published_at"`
	Province         *string    `json:"province"`
	District         *string    `json:"district"`
	Ward             *string    `json:"ward"`
	AssetType        *string    `json:"asset_type"`
	PlotCount        *int32     `json:"plot_count"`
	TotalArea        *string    `json:"total_area"`
	ThumbnailKey     *string    `json:"thumbnail_key"`
	OriginalFileKey  *string    `json:"original_file_key"`
	OriginalFileName *string    `json:"original_file_name"`
	OriginalFileMime *string    `json:"original_file_mime"`
	LegacyID         *int32     `json:"legacy_id"`
	LegacyFileKey    *string    `json:"legacy_file_key"`
	ViewCount        int32      `json:"view_count"`
	CategoryID       *string    `json:"category_id"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	MetaDescription  *string    `json:"meta_description"`
	AuctionStart     *time.Time `json:"auction_start"`
	AuctionEnd       *time.Time `json:"auction_end"`
	VenueName        *string    `json:"venue_name"`
	VenueAddress     *string    `json:"venue_address"`
	StartingPrice    *int64     `json:"starting_price"`
	DepositAmount    *int64     `json:"deposit_amount"`
	CategoryName     *string    `json:"category_name"`
	CategorySlug     *string    `json:"category_slug"`
	CategoryColor    *string    `json:"category_color"`
}

func (q *Queries) GetArticleByID(ctx context.Context, id string) (GetArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i GetArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AuthorName,
		&i.ContentHtml,
		&i.ContentPlain,
		&i.Status,
		&i.PublishedAt,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.AssetType,
		&i.PlotCount,
		&i.TotalArea,
		&i.ThumbnailKey,
		&i.OriginalFileKey,
		&i.OriginalFileName,
		&i.OriginalFileMime,
		&i.LegacyID,
		&i.LegacyFileKey,
		&i.ViewCount,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaDescription,
		&i.AuctionStart,
		&i.AuctionEnd,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartingPrice,
		&i.DepositAmount,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CategoryColor,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT a.id, a.title, a.slug, a.description, a.author_name, a.content_html, a.content_plain,
       a.status, a.published_at, a.province, a.district, a.ward, a.asset_type, a.plot_count,
       a.total_area, a.thumbnail_key, a.original_file_key, a.original_file_name, a.original_file_mime,
       a.legacy_id, a.legacy_file_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.meta_description, a.auction_start, a.auction_end, a.venue_name, a.venue_address,
       a.starting_price, a.deposit_amount,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.slug = $1 AND a.status = 'PUBLISHED'
`

type GetArticleBySlugRow struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Description      string     `json:"description"`
	AuthorName       string     `json:"author_name"`
	ContentHtml      string     `json:"content_html"`
	ContentPlain     string     `json:"content_plain"`
	Status           string     `json:"status"`
	PublishedAt      *time.Time `json:"published_at"`
	Province         *string    `json:"province"`
	District         *string    `json:"district"`
	Ward             *string    `json:"ward"`
	AssetType        *string    `json:"asset_type"`
	PlotCount        *int32     `json:"plot_count"`
	TotalArea        *string    `json:"total_area"`
	ThumbnailKey     *string    `json:"thumbnail_key"`
	OriginalFileKey  *string    `json:"original_file_key"`
	OriginalFileName *string    `json:"original_file_name"`
	OriginalFileMime *string    `json:"original_file_mime"`
	LegacyID         *int32     `json:"legacy_id"`
	LegacyFileKey    *string    `json:"legacy_file_key"`
	ViewCount        int32      `json:"view_count"`
	CategoryID       *string    `json:"category_id"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	MetaDescription  *string    `json:"meta_description"`
	AuctionStart     *time.Time `json:"auction_start"`
	AuctionEnd       *time.Time `json:"auction_end"`
	VenueName        *string    `json:"venue_name"`
	VenueAddress     *string    `json:"venue_address"`
	StartingPrice    *int64     `json:"starting_price"`
	DepositAmount    *int64     `json:"deposit_amount"`
	CategoryName     *string    `json:"category_name"`
	CategorySlug     *string    `json:"category_slug"`
	CategoryColor    *string    `json:"category_color"`
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AuthorName,
		&i.ContentHtml,
		&i.ContentPlain,
		&i.Status,
		&i.PublishedAt,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.AssetType,
		&i.PlotCount,
		&i.TotalArea,
		&i.ThumbnailKey,
		&i.OriginalFileKey,
		&i.OriginalFileName,
		&i.OriginalFileMime,
		&i.LegacyID,
		&i.LegacyFileKey,
		&i.ViewCount,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaDescription,
		&i.AuctionStart,
		&i.AuctionEnd,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartingPrice,
		&i.DepositAmount,
		&i.CategoryName,
		&i.CategorySlug,
		&i.CategoryColor,
	)
	return i, err
}

const getArticleThumbnail = `-- name: GetArticleThumbnail :one
SELECT thumbnail_key, status FROM articles WHERE id = $1
`

type GetArticleThumbnailRow struct {
	ThumbnailKey *string `json:"thumbnail_key"`
	Status       string  `json:"status"`
}

func (q *Queries) GetArticleThumbnail(ctx context.Context, id string) (GetArticleThumbnailRow, error) {
	row := q.db.QueryRow(ctx, getArticleThumbnail, id)
	var i GetArticleThumbnailRow
	err := row.Scan(&i.ThumbnailKey, &i.Status)
	return i, err
}

const incrementViewCount = `-- name: IncrementViewCount :exec
UPDATE articles SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementViewCount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementViewCount, id)
	return err
}

const listAllArticlesSlugs = `-- name: ListAllArticlesSlugs :many
SELECT slug, updated_at FROM articles WHERE status = 'PUBLISHED' ORDER BY published_at DESC
`

type ListAllArticlesSlugsRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListAllArticlesSlugs(ctx context.Context) ([]ListAllArticlesSlugsRow, error) {
	rows, err := q.db.Query(ctx, listAllArticlesSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllArticlesSlugsRow{}
	for rows.Next() {
		var i ListAllArticlesSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.status = 'PUBLISHED'
ORDER BY a.published_at DESC, a.id
LIMIT $1 OFFSET $2
`

type ListPublishedArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedArticlesRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]ListPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesRow{}
	for rows.Next() {
		var i ListPublishedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesByCategory = `-- name: ListPublishedArticlesByCategory :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.status = 'PUBLISHED' AND a.category_id = $1
ORDER BY a.published_at DESC, a.id
LIMIT $2 OFFSET $3
`

type ListPublishedArticlesByCategoryParams struct {
	CategoryID *string `json:"category_id"`
	Limit      int32   `json:"limit"`
	Offset     int32   `json:"offset"`
}

type ListPublishedArticlesByCategoryRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

func (q *Queries) ListPublishedArticlesByCategory(ctx context.Context, arg ListPublishedArticlesByCategoryParams) ([]ListPublishedArticlesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticlesByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesByCategoryRow{}
	for rows.Next() {
		var i ListPublishedArticlesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesByProvince = `-- name: ListPublishedArticlesByProvince :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.status = 'PUBLISHED' AND a.province = $1
ORDER BY a.published_at DESC, a.id
LIMIT $2 OFFSET $3
`

type ListPublishedArticlesByProvinceParams struct {
	Province *string `json:"province"`
	Limit    int32   `json:"limit"`
	Offset   int32   `json:"offset"`
}

type ListPublishedArticlesByProvinceRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

func (q *Queries) ListPublishedArticlesByProvince(ctx context.Context, arg ListPublishedArticlesByProvinceParams) ([]ListPublishedArticlesByProvinceRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticlesByProvince, arg.Province, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesByProvinceRow{}
	for rows.Next() {
		var i ListPublishedArticlesByProvinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesByTag = `-- name: ListPublishedArticlesByTag :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
JOIN article_tags at ON a.id = at.article_id
WHERE a.status = 'PUBLISHED' AND at.tag_id = $1
ORDER BY a.published_at DESC, a.id
LIMIT $2 OFFSET $3
`

type ListPublishedArticlesByTagParams struct {
	TagID  string `json:"tag_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListPublishedArticlesByTagRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
}

func (q *Queries) ListPublishedArticlesByTag(ctx context.Context, arg ListPublishedArticlesByTagParams) ([]ListPublishedArticlesByTagRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticlesByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesByTagRow{}
	for rows.Next() {
		var i ListPublishedArticlesByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishArticle = `-- name: PublishArticle :execrows
UPDATE articles SET status = 'PUBLISHED', published_at = COALESCE(published_at, now()) WHERE id = $1
`

func (q *Queries) PublishArticle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, publishArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchArticles = `-- name: SearchArticles :many
SELECT a.id, a.title, a.slug, a.description, a.author_name,
       a.status, a.published_at, a.province, a.district, a.ward,
       a.thumbnail_key, a.view_count, a.category_id, a.created_at, a.updated_at,
       a.auction_start, a.auction_end, a.starting_price,
       c.name as category_name, c.slug as category_slug, c.color as category_color,
       ts_rank(a.search_vector, plainto_tsquery('vi', $1)) as rank
FROM articles a
LEFT JOIN categories c ON a.category_id = c.id
WHERE a.status = 'PUBLISHED'
  AND a.search_vector @@ plainto_tsquery('vi', $1)
ORDER BY rank DESC, a.published_at DESC, a.id
LIMIT $2 OFFSET $3
`

type SearchArticlesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

type SearchArticlesRow struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Slug          string     `json:"slug"`
	Description   string     `json:"description"`
	AuthorName    string     `json:"author_name"`
	Status        string     `json:"status"`
	PublishedAt   *time.Time `json:"published_at"`
	Province      *string    `json:"province"`
	District      *string    `json:"district"`
	Ward          *string    `json:"ward"`
	ThumbnailKey  *string    `json:"thumbnail_key"`
	ViewCount     int32      `json:"view_count"`
	CategoryID    *string    `json:"category_id"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	AuctionStart  *time.Time `json:"auction_start"`
	AuctionEnd    *time.Time `json:"auction_end"`
	StartingPrice *int64     `json:"starting_price"`
	CategoryName  *string    `json:"category_name"`
	CategorySlug  *string    `json:"category_slug"`
	CategoryColor *string    `json:"category_color"`
	Rank          float32    `json:"rank"`
}

func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchArticles, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.AuthorName,
			&i.Status,
			&i.PublishedAt,
			&i.Province,
			&i.District,
			&i.Ward,
			&i.ThumbnailKey,
			&i.ViewCount,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuctionStart,
			&i.AuctionEnd,
			&i.StartingPrice,
			&i.CategoryName,
			&i.CategorySlug,
			&i.CategoryColor,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleThumbnail = `-- name: SetArticleThumbnail :execrows
UPDATE articles SET thumbnail_key = $1 WHERE id = $2
`

type SetArticleThumbnailParams struct {
	ThumbnailKey *string `json:"thumbnail_key"`
	ID           string  `json:"id"`
}

func (q *Queries) SetArticleThumbnail(ctx context.Context, arg SetArticleThumbnailParams) (int64, error) {
	result, err := q.db.Exec(ctx, setArticleThumbnail, arg.ThumbnailKey, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unpublishArticle = `-- name: UnpublishArticle :execrows
UPDATE articles SET status = 'DRAFT' WHERE id = $1
`

func (q *Queries) UnpublishArticle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, unpublishArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    title = CASE WHEN $1::bool THEN $2 ELSE title END,
    slug = CASE WHEN $3::bool THEN $4 ELSE slug END,
    description = CASE WHEN $5::bool THEN $6 ELSE description END,
    author_name = CASE WHEN $7::bool THEN $8 ELSE author_name END,
    content_html = CASE WHEN $9::bool THEN $10 ELSE content_html END,
    content_plain = CASE WHEN $11::bool THEN $12 ELSE content_plain END,
    province = CASE WHEN $13::bool THEN $14 ELSE province END,
    district = CASE WHEN $15::bool THEN $16 ELSE district END,
    ward = CASE WHEN $17::bool THEN $18 ELSE ward END,
    asset_type = CASE WHEN $19::bool THEN $20 ELSE asset_type END,
    plot_count = CASE WHEN $21::bool THEN $22 ELSE plot_count END,
    total_area = CASE WHEN $23::bool THEN $24 ELSE total_area END,
    category_id = CASE WHEN $25::bool THEN $26 ELSE category_id END,
    meta_description = CASE WHEN $27::bool THEN $28 ELSE meta_description END,
    auction_start = CASE WHEN $29::bool THEN $30 ELSE auction_start END,
    auction_end = CASE WHEN $31::bool THEN $32 ELSE auction_end END,
    venue_name = CASE WHEN $33::bool THEN $34 ELSE venue_name END,
    venue_address = CASE WHEN $35::bool THEN $36 ELSE venue_address END,
    starting_price = CASE WHEN $37::bool THEN $38 ELSE starting_price END,
    deposit_amount = CASE WHEN $39::bool THEN $40 ELSE deposit_amount END
WHERE id = $41
RETURNING id, title, slug, description, author_name, content_html, content_plain,
          status, published_at, province, district, ward, asset_type, plot_count,
          total_area, thumbnail_key, original_file_key, original_file_name, original_file_mime,
          legacy_id, legacy_file_key, view_count, category_id, created_at, updated_at,
          meta_description, auction_start, auction_end, venue_name, venue_address,
          starting_price, deposit_amount
`

type UpdateArticleParams struct {
	SetTitle           bool       `json:"set_title"`
	Title              *string    `json:"title"`
	SetSlug            bool       `json:"set_slug"`
	Slug               *string    `json:"slug"`
	SetDescription     bool       `json:"set_description"`
	Description        *string    `json:"description"`
	SetAuthorName      bool       `json:"set_author_name"`
	AuthorName         *string    `json:"author_name"`
	SetContentHtml     bool       `json:"set_content_html"`
	ContentHtml        *string    `json:"content_html"`
	SetContentPlain    bool       `json:"set_content_plain"`
	ContentPlain       *string    `json:"content_plain"`
	SetProvince        bool       `json:"set_province"`
	Province           *string    `json:"province"`
	SetDistrict        bool       `json:"set_district"`
	District           *string    `json:"district"`
	SetWard            bool       `json:"set_ward"`
	Ward               *string    `json:"ward"`
	SetAssetType       bool       `json:"set_asset_type"`
	AssetType          *string    `json:"asset_type"`
	SetPlotCount       bool       `json:"set_plot_count"`
	PlotCount          *int32     `json:"plot_count"`
	SetTotalArea       bool       `json:"set_total_area"`
	TotalArea          *string    `json:"total_area"`
	SetCategoryID      bool       `json:"set_category_id"`
	CategoryID         *string    `json:"category_id"`
	SetMetaDescription bool       `json:"set_meta_description"`
	MetaDescription    *string    `json:"meta_description"`
	SetAuctionStart    bool       `json:"set_auction_start"`
	AuctionStart       *time.Time `json:"auction_start"`
	SetAuctionEnd      bool       `json:"set_auction_end"`
	AuctionEnd         *time.Time `json:"auction_end"`
	SetVenueName       bool       `json:"set_venue_name"`
	VenueName          *string    `json:"venue_name"`
	SetVenueAddress    bool       `json:"set_venue_address"`
	VenueAddress       *string    `json:"venue_address"`
	SetStartingPrice   bool       `json:"set_starting_price"`
	StartingPrice      *int64     `json:"starting_price"`
	SetDepositAmount   bool       `json:"set_deposit_amount"`
	DepositAmount      *int64     `json:"deposit_amount"`
	ID                 string     `json:"id"`
}

type UpdateArticleRow struct {
	ID               string     `json:"id"`
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	Description      string     `json:"description"`
	AuthorName       string     `json:"author_name"`
	ContentHtml      string     `json:"content_html"`
	ContentPlain     string     `json:"content_plain"`
	Status           string     `json:"status"`
	PublishedAt      *time.Time `json:"published_at"`
	Province         *string    `json:"province"`
	District         *string    `json:"district"`
	Ward             *string    `json:"ward"`
	AssetType        *string    `json:"asset_type"`
	PlotCount        *int32     `json:"plot_count"`
	TotalArea        *string    `json:"total_area"`
	ThumbnailKey     *string    `json:"thumbnail_key"`
	OriginalFileKey  *string    `json:"original_file_key"`
	OriginalFileName *string    `json:"original_file_name"`
	OriginalFileMime *string    `json:"original_file_mime"`
	LegacyID         *int32     `json:"legacy_id"`
	LegacyFileKey    *string    `json:"legacy_file_key"`
	ViewCount        int32      `json:"view_count"`
	CategoryID       *string    `json:"category_id"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	MetaDescription  *string    `json:"meta_description"`
	AuctionStart     *time.Time `json:"auction_start"`
	AuctionEnd       *time.Time `json:"auction_end"`
	VenueName        *string    `json:"venue_name"`
	VenueAddress     *string    `json:"venue_address"`
	StartingPrice    *int64     `json:"starting_price"`
	DepositAmount    *int64     `json:"deposit_amount"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.SetTitle,
		arg.Title,
		arg.SetSlug,
		arg.Slug,
		arg.SetDescription,
		arg.Description,
		arg.SetAuthorName,
		arg.AuthorName,
		arg.SetContentHtml,
		arg.ContentHtml,
		arg.SetContentPlain,
		arg.ContentPlain,
		arg.SetProvince,
		arg.Province,
		arg.SetDistrict,
		arg.District,
		arg.SetWard,
		arg.Ward,
		arg.SetAssetType,
		arg.AssetType,
		arg.SetPlotCount,
		arg.PlotCount,
		arg.SetTotalArea,
		arg.TotalArea,
		arg.SetCategoryID,
		arg.CategoryID,
		arg.SetMetaDescription,
		arg.MetaDescription,
		arg.SetAuctionStart,
		arg.AuctionStart,
		arg.SetAuctionEnd,
		arg.AuctionEnd,
		arg.SetVenueName,
		arg.VenueName,
		arg.SetVenueAddress,
		arg.VenueAddress,
		arg.SetStartingPrice,
		arg.StartingPrice,
		arg.SetDepositAmount,
		arg.DepositAmount,
		arg.ID,
	)
	var i UpdateArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.AuthorName,
		&i.ContentHtml,
		&i.ContentPlain,
		&i.Status,
		&i.PublishedAt,
		&i.Province,
		&i.District,
		&i.Ward,
		&i.AssetType,
		&i.PlotCount,
		&i.TotalArea,
		&i.ThumbnailKey,
		&i.OriginalFileKey,
		&i.OriginalFileName,
		&i.OriginalFileMime,
		&i.LegacyID,
		&i.LegacyFileKey,
		&i.ViewCount,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetaDescription,
		&i.AuctionStart,
		&i.AuctionEnd,
		&i.VenueName,
		&i.VenueAddress,
		&i.StartingPrice,
		&i.DepositAmount,
	)
	return i, err
}
