// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"
	"time"
)

const createArticleAttachment = `-- name: CreateArticleAttachment :one
INSERT INTO article_attachments (id, article_id, file_key, file_name, file_mime, size_bytes, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, article_id, file_key, file_name, file_mime, size_bytes, sort_order, created_at
`

type CreateArticleAttachmentParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FileKey   string `json:"file_key"`
	FileName  string `json:"file_name"`
	FileMime  string `json:"file_mime"`
	SizeBytes int32  `json:"size_bytes"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateArticleAttachment(ctx context.Context, arg CreateArticleAttachmentParams) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, createArticleAttachment,
		arg.ID,
		arg.ArticleID,
		arg.FileKey,
		arg.FileName,
		arg.FileMime,
		arg.SizeBytes,
		arg.SortOrder,
	)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createArticleImage = `-- name: CreateArticleImage :one
INSERT INTO article_images (id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order, created_at
`

type CreateArticleImageParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FileKey   string `json:"file_key"`
	FileName  string `json:"file_name"`
	AltText   string `json:"alt_text"`
	Width     int32  `json:"width"`
	Height    int32  `json:"height"`
	SizeBytes int32  `json:"size_bytes"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateArticleImage(ctx context.Context, arg CreateArticleImageParams) (ArticleImage, error) {
	row := q.db.QueryRow(ctx, createArticleImage,
		arg.ID,
		arg.ArticleID,
		arg.FileKey,
		arg.FileName,
		arg.AltText,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.SortOrder,
	)
	var i ArticleImage
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.AltText,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleAttachment = `-- name: DeleteArticleAttachment :one
DELETE FROM article_attachments WHERE id = $1 AND article_id = $2 RETURNING file_key
`

type DeleteArticleAttachmentParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
}

func (q *Queries) DeleteArticleAttachment(ctx context.Context, arg DeleteArticleAttachmentParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteArticleAttachment, arg.ID, arg.ArticleID)
	var file_key string
	err := row.Scan(&file_key)
	return file_key, err
}

const deleteArticleImage = `-- name: DeleteArticleImage :one
DELETE FROM article_images WHERE id = $1 AND article_id = $2 RETURNING file_key
`

type DeleteArticleImageParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
}

func (q *Queries) DeleteArticleImage(ctx context.Context, arg DeleteArticleImageParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteArticleImage, arg.ID, arg.ArticleID)
	var file_key string
	err := row.Scan(&file_key)
	return file_key, err
}

const getArticleAttachment = `-- name: GetArticleAttachment :one
SELECT at.id, at.article_id, at.file_key, at.file_name, at.file_mime, at.size_bytes,
       at.sort_order, at.created_at, a.status AS article_status
FROM article_attachments at
JOIN articles a ON a.id = at.article_id
WHERE at.id = $1 AND at.article_id = $2
`

type GetArticleAttachmentParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
}

type GetArticleAttachmentRow struct {
	ID            string    `json:"id"`
	ArticleID     string    `json:"article_id"`
	FileKey       string    `json:"file_key"`
	FileName      string    `json:"file_name"`
	FileMime      string    `json:"file_mime"`
	SizeBytes     int32     `json:"size_bytes"`
	SortOrder     int32     `json:"sort_order"`
	CreatedAt     time.Time `json:"created_at"`
	ArticleStatus string    `json:"article_status"`
}

func (q *Queries) GetArticleAttachment(ctx context.Context, arg GetArticleAttachmentParams) (GetArticleAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getArticleAttachment, arg.ID, arg.ArticleID)
	var i GetArticleAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ArticleStatus,
	)
	return i, err
}

const getArticleImage = `-- name: GetArticleImage :one
SELECT i.id, i.article_id, i.file_key, i.file_name, i.alt_text, i.width, i.height,
       i.size_bytes, i.sort_order, i.created_at, a.status AS article_status
FROM article_images i
JOIN articles a ON a.id = i.article_id
WHERE i.id = $1
`

type GetArticleImageRow struct {
	ID            string    `json:"id"`
	ArticleID     string    `json:"article_id"`
	FileKey       string    `json:"file_key"`
	FileName      string    `json:"file_name"`
	AltText       string    `json:"alt_text"`
	Width         int32     `json:"width"`
	Height        int32     `json:"height"`
	SizeBytes     int32     `json:"size_bytes"`
	SortOrder     int32     `json:"sort_order"`
	CreatedAt     time.Time `json:"created_at"`
	ArticleStatus string    `json:"article_status"`
}

func (q *Queries) GetArticleImage(ctx context.Context, id string) (GetArticleImageRow, error) {
	row := q.db.QueryRow(ctx, getArticleImage, id)
	var i GetArticleImageRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.AltText,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
		&i.ArticleStatus,
	)
	return i, err
}

const listArticleAttachments = `-- name: ListArticleAttachments :many
SELECT id, article_id, file_key, file_name, file_mime, size_bytes, sort_order, created_at FROM article_attachments WHERE article_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListArticleAttachments(ctx context.Context, articleID string) ([]ArticleAttachment, error) {
	rows, err := q.db.Query(ctx, listArticleAttachments, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleAttachment{}
	for rows.Next() {
		var i ArticleAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.FileKey,
			&i.FileName,
			&i.FileMime,
			&i.SizeBytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleImages = `-- name: ListArticleImages :many
SELECT id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order, created_at FROM article_images WHERE article_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListArticleImages(ctx context.Context, articleID string) ([]ArticleImage, error) {
	rows, err := q.db.Query(ctx, listArticleImages, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleImage{}
	for rows.Next() {
		var i ArticleImage
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.FileKey,
			&i.FileName,
			&i.AltText,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleAttachmentName = `-- name: UpdateArticleAttachmentName :execrows
UPDATE article_attachments SET file_name = $3 WHERE id = $1 AND article_id = $2
`

type UpdateArticleAttachmentNameParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FileName  string `json:"file_name"`
}

func (q *Queries) UpdateArticleAttachmentName(ctx context.Context, arg UpdateArticleAttachmentNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateArticleAttachmentName, arg.ID, arg.ArticleID, arg.FileName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticleImageAlt = `-- name: UpdateArticleImageAlt :execrows
UPDATE article_images SET alt_text = $3 WHERE id = $1 AND article_id = $2
`

type UpdateArticleImageAltParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	AltText   string `json:"alt_text"`
}

func (q *Queries) UpdateArticleImageAlt(ctx context.Context, arg UpdateArticleImageAltParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateArticleImageAlt, arg.ID, arg.ArticleID, arg.AltText)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticleImageOrder = `-- name: UpdateArticleImageOrder :execrows
UPDATE article_images SET sort_order = $3 WHERE id = $1 AND article_id = $2
`

type UpdateArticleImageOrderParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateArticleImageOrder(ctx context.Context, arg UpdateArticleImageOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateArticleImageOrder, arg.ID, arg.ArticleID, arg.SortOrder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
