// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"
)

const createArticleAttachment = `-- name: CreateArticleAttachment :one
INSERT INTO article_attachments (id, article_id, file_key, file_name, file_mime, size_bytes, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, article_id, file_key, file_name, file_mime, size_bytes, sort_order, created_at
`

type CreateArticleAttachmentParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FileKey   string `json:"file_key"`
	FileName  string `json:"file_name"`
	FileMime  string `json:"file_mime"`
	SizeBytes int32  `json:"size_bytes"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateArticleAttachment(ctx context.Context, arg CreateArticleAttachmentParams) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, createArticleAttachment,
		arg.ID,
		arg.ArticleID,
		arg.FileKey,
		arg.FileName,
		arg.FileMime,
		arg.SizeBytes,
		arg.SortOrder,
	)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createArticleImage = `-- name: CreateArticleImage :one
INSERT INTO article_images (id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order, created_at
`

type CreateArticleImageParams struct {
	ID        string `json:"id"`
	ArticleID string `json:"article_id"`
	FileKey   string `json:"file_key"`
	FileName  string `json:"file_name"`
	AltText   string `json:"alt_text"`
	Width     int32  `json:"width"`
	Height    int32  `json:"height"`
	SizeBytes int32  `json:"size_bytes"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateArticleImage(ctx context.Context, arg CreateArticleImageParams) (ArticleImage, error) {
	row := q.db.QueryRow(ctx, createArticleImage,
		arg.ID,
		arg.ArticleID,
		arg.FileKey,
		arg.FileName,
		arg.AltText,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.SortOrder,
	)
	var i ArticleImage
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.AltText,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleAttachment = `-- name: DeleteArticleAttachment :one
DELETE FROM article_attachments WHERE id = $1 RETURNING file_key
`

func (q *Queries) DeleteArticleAttachment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteArticleAttachment, id)
	var file_key string
	err := row.Scan(&file_key)
	return file_key, err
}

const deleteArticleImage = `-- name: DeleteArticleImage :one
DELETE FROM article_images WHERE id = $1 RETURNING file_key
`

func (q *Queries) DeleteArticleImage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteArticleImage, id)
	var file_key string
	err := row.Scan(&file_key)
	return file_key, err
}

const getArticleAttachment = `-- name: GetArticleAttachment :one
SELECT id, article_id, file_key, file_name, file_mime, size_bytes, sort_order, created_at FROM article_attachments WHERE id = $1
`

func (q *Queries) GetArticleAttachment(ctx context.Context, id string) (ArticleAttachment, error) {
	row := q.db.QueryRow(ctx, getArticleAttachment, id)
	var i ArticleAttachment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.FileMime,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getArticleImage = `-- name: GetArticleImage :one
SELECT id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order, created_at FROM article_images WHERE id = $1
`

func (q *Queries) GetArticleImage(ctx context.Context, id string) (ArticleImage, error) {
	row := q.db.QueryRow(ctx, getArticleImage, id)
	var i ArticleImage
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.FileKey,
		&i.FileName,
		&i.AltText,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listArticleAttachments = `-- name: ListArticleAttachments :many
SELECT id, article_id, file_key, file_name, file_mime, size_bytes, sort_order, created_at FROM article_attachments WHERE article_id = $1 ORDER BY sort_order
`

func (q *Queries) ListArticleAttachments(ctx context.Context, articleID string) ([]ArticleAttachment, error) {
	rows, err := q.db.Query(ctx, listArticleAttachments, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleAttachment{}
	for rows.Next() {
		var i ArticleAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.FileKey,
			&i.FileName,
			&i.FileMime,
			&i.SizeBytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleImages = `-- name: ListArticleImages :many
SELECT id, article_id, file_key, file_name, alt_text, width, height, size_bytes, sort_order, created_at FROM article_images WHERE article_id = $1 ORDER BY sort_order
`

func (q *Queries) ListArticleImages(ctx context.Context, articleID string) ([]ArticleImage, error) {
	rows, err := q.db.Query(ctx, listArticleImages, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleImage{}
	for rows.Next() {
		var i ArticleImage
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.FileKey,
			&i.FileName,
			&i.AltText,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleAttachmentName = `-- name: UpdateArticleAttachmentName :exec
UPDATE article_attachments SET file_name = $2 WHERE id = $1
`

type UpdateArticleAttachmentNameParams struct {
	ID       string `json:"id"`
	FileName string `json:"file_name"`
}

func (q *Queries) UpdateArticleAttachmentName(ctx context.Context, arg UpdateArticleAttachmentNameParams) error {
	_, err := q.db.Exec(ctx, updateArticleAttachmentName, arg.ID, arg.FileName)
	return err
}

const updateArticleAttachmentOrder = `-- name: UpdateArticleAttachmentOrder :exec
UPDATE article_attachments SET sort_order = $2 WHERE id = $1
`

type UpdateArticleAttachmentOrderParams struct {
	ID        string `json:"id"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateArticleAttachmentOrder(ctx context.Context, arg UpdateArticleAttachmentOrderParams) error {
	_, err := q.db.Exec(ctx, updateArticleAttachmentOrder, arg.ID, arg.SortOrder)
	return err
}

const updateArticleImageAlt = `-- name: UpdateArticleImageAlt :exec
UPDATE article_images SET alt_text = $2 WHERE id = $1
`

type UpdateArticleImageAltParams struct {
	ID      string `json:"id"`
	AltText string `json:"alt_text"`
}

func (q *Queries) UpdateArticleImageAlt(ctx context.Context, arg UpdateArticleImageAltParams) error {
	_, err := q.db.Exec(ctx, updateArticleImageAlt, arg.ID, arg.AltText)
	return err
}

const updateArticleImageOrder = `-- name: UpdateArticleImageOrder :exec
UPDATE article_images SET sort_order = $2 WHERE id = $1
`

type UpdateArticleImageOrderParams struct {
	ID        string `json:"id"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpdateArticleImageOrder(ctx context.Context, arg UpdateArticleImageOrderParams) error {
	_, err := q.db.Exec(ctx, updateArticleImageOrder, arg.ID, arg.SortOrder)
	return err
}
