// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID               string      `json:"id"`
	Title            string      `json:"title"`
	Slug             string      `json:"slug"`
	Description      string      `json:"description"`
	AuthorName       string      `json:"author_name"`
	ContentHtml      string      `json:"content_html"`
	ContentPlain     string      `json:"content_plain"`
	Status           string      `json:"status"`
	PublishedAt      *time.Time  `json:"published_at"`
	Province         *string     `json:"province"`
	District         *string     `json:"district"`
	Ward             *string     `json:"ward"`
	AssetType        *string     `json:"asset_type"`
	PlotCount        pgtype.Int4 `json:"plot_count"`
	TotalArea        *string     `json:"total_area"`
	ThumbnailKey     *string     `json:"thumbnail_key"`
	OriginalFileKey  *string     `json:"original_file_key"`
	OriginalFileName *string     `json:"original_file_name"`
	OriginalFileMime *string     `json:"original_file_mime"`
	LegacyID         pgtype.Int4 `json:"legacy_id"`
	LegacyFileKey    *string     `json:"legacy_file_key"`
	ViewCount        int32       `json:"view_count"`
	CategoryID       *string     `json:"category_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	SearchVector     interface{} `json:"search_vector"`
}

type ArticleAttachment struct {
	ID        string    `json:"id"`
	ArticleID string    `json:"article_id"`
	FileKey   string    `json:"file_key"`
	FileName  string    `json:"file_name"`
	FileMime  string    `json:"file_mime"`
	SizeBytes int32     `json:"size_bytes"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type ArticleImage struct {
	ID        string    `json:"id"`
	ArticleID string    `json:"article_id"`
	FileKey   string    `json:"file_key"`
	FileName  string    `json:"file_name"`
	AltText   string    `json:"alt_text"`
	Width     int32     `json:"width"`
	Height    int32     `json:"height"`
	SizeBytes int32     `json:"size_bytes"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type ArticleTag struct {
	ArticleID string `json:"article_id"`
	TagID     string `json:"tag_id"`
}

type Category struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Color     string    `json:"color"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Tag struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ViewEvent struct {
	ID        string    `json:"id"`
	ArticleID string    `json:"article_id"`
	ViewedAt  time.Time `json:"viewed_at"`
	IpHash    string    `json:"ip_hash"`
	UserAgent *string   `json:"user_agent"`
	Referrer  *string   `json:"referrer"`
}
