// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const addArticleTag = `-- name: AddArticleTag :exec
INSERT INTO article_tags (article_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddArticleTagParams struct {
	ArticleID string `json:"article_id"`
	TagID     string `json:"tag_id"`
}

func (q *Queries) AddArticleTag(ctx context.Context, arg AddArticleTagParams) error {
	_, err := q.db.Exec(ctx, addArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_at
`

type CreateTagParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, slug, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, created_at FROM tags WHERE slug = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, created_at FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByArticle = `-- name: ListTagsByArticle :many
SELECT t.id, t.name, t.slug, t.created_at FROM tags t
JOIN article_tags at ON t.id = at.tag_id
WHERE at.article_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsByArticle(ctx context.Context, articleID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllArticleTags = `-- name: RemoveAllArticleTags :exec
DELETE FROM article_tags WHERE article_id = $1
`

func (q *Queries) RemoveAllArticleTags(ctx context.Context, articleID string) error {
	_, err := q.db.Exec(ctx, removeAllArticleTags, articleID)
	return err
}

const removeArticleTag = `-- name: RemoveArticleTag :exec
DELETE FROM article_tags WHERE article_id = $1 AND tag_id = $2
`

type RemoveArticleTagParams struct {
	ArticleID string `json:"article_id"`
	TagID     string `json:"tag_id"`
}

func (q *Queries) RemoveArticleTag(ctx context.Context, arg RemoveArticleTagParams) error {
	_, err := q.db.Exec(ctx, removeArticleTag, arg.ArticleID, arg.TagID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, name, slug)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, slug, created_at
`

type UpsertTagParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.ID, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
