// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countViewsByArticle = `-- name: CountViewsByArticle :one
SELECT count(*) FROM view_events WHERE article_id = $1
`

func (q *Queries) CountViewsByArticle(ctx context.Context, articleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countViewsByArticle, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createViewEvent = `-- name: CreateViewEvent :exec
INSERT INTO view_events (id, article_id, ip_hash, user_agent, referrer)
VALUES ($1, $2, $3, $4, $5)
`

type CreateViewEventParams struct {
	ID        string  `json:"id"`
	ArticleID string  `json:"article_id"`
	IpHash    string  `json:"ip_hash"`
	UserAgent *string `json:"user_agent"`
	Referrer  *string `json:"referrer"`
}

func (q *Queries) CreateViewEvent(ctx context.Context, arg CreateViewEventParams) error {
	_, err := q.db.Exec(ctx, createViewEvent,
		arg.ID,
		arg.ArticleID,
		arg.IpHash,
		arg.UserAgent,
		arg.Referrer,
	)
	return err
}

const recentViewsByArticle = `-- name: RecentViewsByArticle :many
SELECT date_trunc('day', viewed_at)::date as day, count(*) as views
FROM view_events
WHERE article_id = $1 AND viewed_at > now() - interval '30 days'
GROUP BY day
ORDER BY day
`

type RecentViewsByArticleRow struct {
	Day   pgtype.Date `json:"day"`
	Views int64       `json:"views"`
}

func (q *Queries) RecentViewsByArticle(ctx context.Context, articleID string) ([]RecentViewsByArticleRow, error) {
	rows, err := q.db.Query(ctx, recentViewsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentViewsByArticleRow{}
	for rows.Next() {
		var i RecentViewsByArticleRow
		if err := rows.Scan(&i.Day, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
